# Generated by Django 5.0.2 on 2024-03-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludotec_app', '0003_alter_tematica_nombre_tematica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mecanica',
            name='nombre_mecanica',
            field=models.CharField(blank=True, choices=[('push_your_luck', 'Push Your Luck'), ('gestion_de_mano', 'Gestión de mano'), ('deckbuilding', 'Deckbuilding'), ('colocacion_de_trabajadores', 'Colocación de Trabajadores'), ('colocacion_de_losetas', 'Colocación de losetas'), ('roll_and_write', 'Roll & Write'), ('draft', 'Draft'), ('control_de_area', 'Control de área'), ('card_driven', 'Card Driven'), ('apuestas', 'Apuestas'), ('subastas', 'Subastas'), ('faroleo', 'Faroleo'), ('economico', 'Económico'), ('comercio/negociacion', 'Comercio/Negociación'), ('cooperativo', 'Cooperativo'), ('solitario', 'Solitario'), ('roles_ocultos', 'Roles ocultos'), ('deduccion', 'Deducción'), ('bazas', 'Bazas'), ('carrera', 'Carrera'), ('set_collection', 'Set Collection'), ('flicking', 'Flicking'), ('destreza', 'Destreza'), ('tiempo_real', 'Tiempo real'), ('memoria', 'Memoria'), ('dibujo', 'Dibujo')], max_length=100),
        ),
        migrations.AlterField(
            model_name='tematica',
            name='nombre_tematica',
            field=models.CharField(blank=True, choices=[('animales', 'Animales'), ('aventuras_exploracion', 'Aventuras y exploración'), ('deportes', 'Deportes'), ('abstracto', 'Abstracto'), ('agricultura', 'Agricultura'), ('arte/literatura', 'Arte/Literatura'), ('carreras', 'Carreras'), ('ciencia_ficcion', 'Ciencia Ficción'), ('civilizaciones', 'Civilizaciones'), ('comercio', 'Comercio'), ('construccion_ciudades', 'Construcción de ciudades'), ('misterio', 'Misterio'), ('comida/bebida', 'Comidas/Bebidas'), ('fantasia', 'Fantasía'), ('familiar', 'Familiar'), ('guerra', 'Guerra'), ('historia', 'Historia'), ('medicina', 'Medicina'), ('medieval', 'Medieval'), ('naturaleza', 'Naturaleza'), ('oeste', 'Oeste'), ('oriental', 'Oriental'), ('party', 'Party'), ('piratas', 'Piratas'), ('politica', 'Política'), ('terror', 'Terror'), ('trenes', 'Trenes'), ('tv/series/cine', 'Tv/Series/Cine'), ('zombies', 'Zombies')], max_length=100),
        ),
    ]
