# Generated by Django 5.0.3 on 2024-03-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludotec_app', '0004_alter_mecanica_nombre_mecanica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mecanica',
            name='nombre_mecanica',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tematica',
            name='nombre_tematica',
            field=models.CharField(max_length=200),
        ),
    ]
