# Generated by Django 5.0.3 on 2024-05-07 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludotec_app', '0006_jugador_partida_puntuacion_partida_jugadores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='juego',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ludotec_app.juego'),
        ),
    ]
