# Generated by Django 5.0.3 on 2024-05-14 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludotec_app', '0009_informacionjuego_alter_partida_juego'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacionjuego',
            name='juego',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ludotec_app.juego'),
        ),
    ]
