# Generated by Django 5.0.3 on 2024-05-14 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludotec_app', '0013_alter_partida_juego_delete_informacionjuego'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='juego',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ludotec_app.juego'),
        ),
    ]
