# Generated by Django 5.0.3 on 2024-05-14 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludotec_app', '0014_alter_partida_juego'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='juego',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ludotec_app.juego'),
        ),
    ]
