# Generated by Django 5.0.3 on 2024-05-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludotec_app', '0017_alter_partida_juego'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='nombre_juego',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
