# Generated by Django 5.0.3 on 2024-05-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludotec_app', '0018_partida_nombre_juego'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='ludotec_app/boardgames-images/'),
        ),
    ]
