# Generated by Django 5.0.3 on 2024-05-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludotec_app', '0020_alter_juego_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
