# Generated by Django 5.0.3 on 2024-06-19 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludotec_app', '0026_puntuacion_ganador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puntuacion',
            name='ganador',
        ),
        migrations.AddField(
            model_name='partida',
            name='ganador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidas_ganadas', to='ludotec_app.jugador'),
        ),
    ]
