# Generated by Django 5.0.3 on 2024-06-19 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ludotec_app', '0027_remove_puntuacion_ganador_partida_ganador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partida',
            name='ganador',
        ),
    ]
