# Generated by Django 5.0.3 on 2024-06-22 00:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludotec_app', '0029_puntuacion_ganador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='año',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2024)]),
        ),
        migrations.AlterField(
            model_name='juego',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='juego',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='tematica',
            name='nombre_tematica',
            field=models.CharField(max_length=100),
        ),
    ]
